#ifndef CONFIG_H
#define CONFIG_H

#define WIDTH 512
#define HEIGHT 512
#define SCALE 1
#define RECURSION_MAX 6
#define MAXDISTANCE 128
#define SUPERSAMPLINGLEVEL 4
#define SUPERSAMPLINGJITTER 0.001f

#endif