#ifndef CONFIG_H
#define CONFIG_H

#define WIDTH 128
#define HEIGHT 128
#define SCALE 4
#define RECURSION_MAX 5
#define MAXDISTANCE 128
#define SUPERSAMPLINGLEVEL 0
#define SUPERSAMPLINGJITTER 0.001f

#endif
